# Arquivo de chamada das perdas de protensão segundo CATOIA 2011

SIGMA_PIT1 = 100e3;
P_IT1 = 10e3;


[DELTAPERC, P_IT1, SIGMA_PIT1]=PERDA_DESLIZAMENTO_ANCORAGEM(P_IT0, SIGMA_PIT0, A_SCP, L_0, DELTA_ANC, E_SCP);

[DELTAPERC, P_IT1, SIGMA_PIT1]=PERDA_RELAXACAO_ARMADURA(P_IT0, SIGMA_PIT0, T_0, T_1, TEMP, F_PK, A_SCP, TIPO_FIO_CORD_BAR, TIPO_ACO):

[DELTAPERC, P_IT1, SIGMA_PIT1]=PERDA_DEFORMACAO_CONCRETO(E_SCP, E_CCP, P_IT0, SIGMA_PIT0, A_C, I_C, E_P, M_GPP):

[DELTAPERC, P_IT1, SIGMA_PIT1]=PERDA_RETRACAO_CONCRETO(U, ABAT)

[PHI_T1_T0,DELTA_SIGMA_FLU]=PERDA_POR_FLUENCIA_NO_CONCRETO(T_0,T_1,F_CKJ,F_CK,U,A_SPM,PERIM,T,E_PROTE,E_CI,SIGMA_CGP,A_P,ABATIMENTO,SIGMA_PI)

[DELTAPERC, P_IT1, SIGMA_PIT1]=PERDA_RELAXACAO_ARMADURA(P_IT0, SIGMA_PIT0, T_0, T_1, TEMP, F_PK, A_SCP, TIPO_FIO_CORD_BAR, TIPO_ACO):

